version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pdf-viewer-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: pdf_viewer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - pdf_viewer_postgres_data:/var/lib/postgresql/data

volumes:
  pdf_viewer_postgres_data: